# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 901, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.readCsvButton = QtWidgets.QPushButton(self.centralwidget)
        self.readCsvButton.setGeometry(QtCore.QRect(600, 490, 93, 28))
        self.readCsvButton.setObjectName("readCsvButton")
        self.saveChangesButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveChangesButton.setGeometry(QtCore.QRect(800, 490, 93, 28))
        self.saveChangesButton.setObjectName("saveChangesButton")
        self.readExelButton = QtWidgets.QPushButton(self.centralwidget)
        self.readExelButton.setGeometry(QtCore.QRect(700, 490, 93, 28))
        self.readExelButton.setObjectName("readExelButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 26))
        self.menubar.setObjectName("menubar")
        self.menug = QtWidgets.QMenu(self.menubar)
        self.menug.setObjectName("menug")
        self.menucontacts = QtWidgets.QMenu(self.menubar)
        self.menucontacts.setObjectName("menucontacts")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenCsv = QtWidgets.QAction(MainWindow)
        self.actionOpenCsv.setObjectName("actionOpenCsv")
        self.actionFindContact = QtWidgets.QAction(MainWindow)
        self.actionFindContact.setObjectName("actionFindContact")
        self.actionOpenExel = QtWidgets.QAction(MainWindow)
        self.actionOpenExel.setObjectName("actionOpenExel")
        self.menug.addAction(self.actionOpenCsv)
        self.menug.addAction(self.actionOpenExel)
        self.menucontacts.addAction(self.actionFindContact)
        self.menubar.addAction(self.menug.menuAction())
        self.menubar.addAction(self.menucontacts.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "firstname"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "lastname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "phone number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "age"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "address"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "info1"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "info2"))
        self.readCsvButton.setText(_translate("MainWindow", "read csv file"))
        self.saveChangesButton.setText(_translate("MainWindow", "save changes"))
        self.readExelButton.setText(_translate("MainWindow", "read exel file"))
        self.menug.setTitle(_translate("MainWindow", "file"))
        self.menucontacts.setTitle(_translate("MainWindow", "contacts"))
        self.actionOpenCsv.setText(_translate("MainWindow", "open csv"))
        self.actionFindContact.setText(_translate("MainWindow", "find"))
        self.actionOpenExel.setText(_translate("MainWindow", "open exel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
